name: WorldMaster
author: JDDev0
version: 1.0.2
api-version: 1.15
main: me.jddev0.Plugin
description: World commands and other utilities

commands:
    world:
        description: World command
        usage: §c/world <add|remove|renew|set_join_gamemode|set_permission|set_allowed_gamemodes|set_time|set_difficulty|list|tp> [<name>] [<gamemode>|<gamemodes...>|<type>|<time>|<difficulty>] [<permission>]
    permission:
        description: Permission command
        usage: §c/permission <allow|disallow|default> <player> <permission>
        permission: worldmaster.permission
        permission-message: §cYou don't have the permission for this command
    elevator:
        description: Elevator command
        usage: §c/elevator <make|create|remove|add_floor|remove_floor|set_speed|move> [<name>|<floorName>] [<floorHeight>|<floorName>|<speed>] [<doorPos>] [<permission>]
    teleporter:
        description: Teleporter command
        usage: §c/teleporter <create|delete|give|add|remove|add_position|remove_position> <name>|<positon_name>|<slot> [<position_name>|<icon>] [<slot>|<world_name>] [<coords>]
    chunk_loader:
        description: Chunk loader command
        usage: §c/chunk_loader
        permission: worldmaster.chunk_loader
        permission-message: §cYou don't have the permission for this command
    inventory:
        description: Inventory command
        usage: §c/inventory <list>|<add>|<remove>|<list_world>|<add_world>|<remove_world> [<name>] [<world>]
        permission: worldmaster.inventory
        permission-message: §cYou don't have the permission for this command
    reload_config:
        description: Reload config command
        usage: §c/reload_config
        permission: worldmaster.reload_config
        permission-message: §cYou don't have the permission for this command

permissions:
    world:
        description: Use the world command
        default: op
    permission:
        description: Use the permission command
        default: op
    elevator:
        description: Use the elevator command
        default: op
    teleporter:
        description: Use the teleporter command
        default: op
    chunk_loader:
        description: Use the chunk_loader command
        default: op
    reload_config:
        description: Use the reload_config command
        default: op
    inventory:
        description: Use the inventory command
        default: op
    build_spawn:
        description: Can build in spawn world
        default: op
    shop_owner:
        description: Can create shop
        default: true
